kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging.prod-fss-pub.nais.io
    - https://veilarboppfolging.nais.adeo.no
    - https://app.adeo.no/veilarboppfolging
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/health/liveness
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/health/readiness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
          cluster: prod-gcp
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-fss
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: paw-proxy
          namespace: paw
        - application: veilarbperson
          namespace: pto
          cluster: prod-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: modia-robot-api
          namespace: personoversikt
          cluster: prod-fss
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarboppfolging-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarboppfolging/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/prod/config/veilarboppfolging
        mountPath: /var/run/secrets/nais.io/oracle_config
  env:
    - name: MODIABLOGIN_OPENAM_CLIENT_ID
      value: "modialogin-p"
    - name: VEILARBREGISTRERING_CLIENT_ID
      value: b898d7c6-0160-4dca-867e-873a4bd85d25

    # producer topics
    - name: ENDRING_PAA_AVSLUTT_OPPFOLGING_TOPIC
      value: aapen-fo-endringPaaAvsluttOppfolging-v1-p
    - name: OPPFOLGING_STARTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingStartet-v1-p
    - name: OPPFOLGING_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-p
    - name: KVP_STARTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpStartet-v1-p
    - name: KVP_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpAvsluttet-v1-p
    - name: ENDRING_PA_MAL_TOPIC
      value: aapen-arbeidsrettetOppfolging-endringPaMal-v1-p
