kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: poao
  labels:
    team: poao
spec:
  image: {{image}}
  ingresses:
    - https://veilarboppfolging.intern.dev.nav.no
  port: 8080
  gcp:
    bigQueryDatasets:
      - description: Metrikker for veilarboppfolging
        name: oppfolging_metrikker
        permission: READWRITE
      - description: Metrikker for overvåkning av kontorbrukere
        name: kontor_metrikker
        permission: READWRITE
    sqlInstances:
      - name: veilarboppfolging
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        diskAutoresize: true
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: veilarboppfolging
            envVarPrefix: DB
            users:
              - name: datastream
              - name: veilarboppfolging_midlertidig # Bruker uten write-rettigheter
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/health/liveness
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/health/readiness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: http://digdir-krr-proxy.team-rocket
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: AMTDELTAKER_URL
      value: http://amt-deltaker.amt
    - name: AMTDELTAKER_SCOPE
      value: api://dev-gcp.amt.amt-deltaker/.default
    - name: KAFKA_ENABLED
      value: "true"
    - name: VEILARBARENA_URL
      value: "https://veilarbarena.dev-fss-pub.nais.io"
    - name: VEILARBARENA_AZURE_SCOPE
      value: "api://dev-fss.pto.veilarbarena/.default"
    - name: NORG2_URL
      value: "http://norg2.org/norg2"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDL_BEHANDLINGSNUMMER
      value: "B884"
    - name: NAV_NO_URL
      value: "https://www.ansatt.dev.nav.no"
    - name: EXPOSE_GRAPHIQL
      value: "true"
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: veilarbarena
          namespace: pto
          cluster: dev-fss
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: poao-tilgang
        - application: amt-deltaker
          namespace: amt
        - application: norg2
          namespace: org
        - application: logging
          namespace: nais-system
      external:
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: paw-proxy
          namespace: paw
        - application: veilarbperson
          namespace: obo
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: dev-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: modia-robot-api
          namespace: personoversikt
          cluster: dev-gcp
        - application: modiapersonoversikt-api-q1
          namespace: personoversikt
          cluster: dev-fss
        - application: ditt-sykefravaer
          namespace: flex
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: dab
        - application: veilarbdialog
          namespace: dab
          cluster: dev-gcp
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
        - application: amt-person-service
          namespace: amt
          cluster: dev-gcp
        - application: amt-aktivitetskort-publisher
          namespace: amt
          cluster: dev-gcp
        - application: tms-min-side-proxy
          namespace: min-side
          cluster: dev-gcp
        - application: tms-mikrofrontend-selector
          namespace: min-side
          cluster: dev-gcp
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: amt-distribusjon
          namespace: amt
          cluster: dev-gcp
        - application: dokumentfordeling
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: inngar
          namespace: dab
        - application: statuspoll
          namespace: navdig
        - application: tiltakspenger-saksbehandling-api
          namespace: tpts
        - application: pto-admin
          namespace: pto
          cluster: dev-fss
        - application: poao-admin
          namespace: poao
          cluster: dev-gcp
        - application: oppgave
          namespace: aap
          cluster: dev-gcp
        - application: ao-min-side-microfrontend
          namespace: dab
          cluster: dev-gcp
        - application: ao-min-side-microfrontend-ssr
          namespace: dab
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss # Dette er med vilje