kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: {{namespace}}
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarboppfolging
  leaderElection: true
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarboppfolging_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarboppfolging/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
