kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: default
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging.nais.adeo.no
    - https://app.adeo.no/veilarboppfolging
  leaderElection: true
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/isAlive
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/isReady
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
  envFrom:
    - configmap: pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarboppfolging-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarboppfolging/default
        mountPath: /var/run/secrets/nais.io/vault
