kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging.dev-fss-pub.nais.io
    - https://veilarboppfolging.dev.intern.nav.no
    - https://veilarboppfolging-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarboppfolging
    - https://app-q1.dev.adeo.no/veilarboppfolging
    - https://app.dev.adeo.no/veilarboppfolging
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/health/liveness
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/health/readiness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.nais.local
    - name: POAO_TILGANG_SCOPE
      value: api://dev-fss.poao.poao-tilgang/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.dev.intern.nav.no
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
          cluster: dev-gcp
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: dev-gcp
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: paw-proxy
          namespace: paw
        - application: veilarbperson
          namespace: pto
          cluster: dev-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: modia-robot-api
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt-api-q1
          namespace: personoversikt
          cluster: dev-fss
        - application: ditt-sykefravaer
          namespace: flex
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: veilarbdialog
          namespace: pto
          cluster: dev-fss
        - application: veilarbaktivitet
          namespace: pto
          cluster: dev-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
        - application: esyfo-info-frontend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: amt-person-service
          namespace: amt
          cluster: dev-gcp
        - application: tms-min-side-proxy
          namespace: min-side
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarboppfolging_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarboppfolging/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarboppfolging_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
