kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarboppfolging
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarboppfolging/veilarboppfolging:{{version}}
  ingresses:
    - https://veilarboppfolging.prod-fss-pub.nais.io
    - https://veilarboppfolging.nais.adeo.no
    - https://app.adeo.no/veilarboppfolging
    - https://veilarboppfolging.intern.nav.no
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarboppfolging/internal/prometheus
  liveness:
    path: veilarboppfolging/internal/health/liveness
    initialDelay: 30
  readiness:
    path: veilarboppfolging/internal/health/readiness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
          namespace: amt
          cluster: prod-gcp
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-fss
        - application: veilarbregistrering
          namespace: paw
          cluster: prod-gcp
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: paw-proxy
          namespace: paw
        - application: veilarbperson
          namespace: pto
          cluster: prod-fss
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: prod-fss
        - application: modia-robot-api
          namespace: personoversikt
          cluster: prod-fss
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: prod-fss
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: prod-fss
        - application: veilarbdialog
          namespace: pto
          cluster: prod-fss
        - application: veilarbaktivitet
          namespace: pto
          cluster: prod-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: prod-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: prod-gcp
        - application: start-samtale
          namespace: pto
          cluster: prod-gcp
        - application: esyfo-info-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: amt-person-service
          namespace: amt
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarboppfolging-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarboppfolging
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarboppfolging/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/prod/config/veilarboppfolging
        mountPath: /var/run/secrets/nais.io/oracle_config

