CREATE INDEX "VEILARBOPPFOLGING"."OPPFOLGINGSPERIODE_INDEX1" ON "VEILARBOPPFOLGING"."OPPFOLGINGSPERIODE" ("AKTOR_ID");
CREATE INDEX "VEILARBOPPFOLGING"."MAL_AKTOERID_INDEX" ON "VEILARBOPPFOLGING"."MAL" ("AKTOR_ID");
CREATE INDEX "VEILARBOPPFOLGING"."VILKAR_AKTOERID_INDEX" ON "VEILARBOPPFOLGING"."BRUKERVILKAR" ("AKTOR_ID");