ALTER TABLE BRUKER_REGISTRERING add NUS_KODE VARCHAR(6);
ALTER TABLE BRUKER_REGISTRERING add STYRK_KODE VARCHAR(6);
ALTER TABLE BRUKER_REGISTRERING add UTDANNING_BESTATT NUMBER(1,0);
ALTER TABLE BRUKER_REGISTRERING add UTDANNING_GODKJENT_NORGE NUMBER(1,0);
ALTER TABLE BRUKER_REGISTRERING add FORESLATT_VERDIER_EGET_YRKE NUMBER(1,0);
ALTER TABLE BRUKER_REGISTRERING add UTDANNINGSNIVA VARCHAR(20);
