CREATE SEQUENCE KVP_SEQ START WITH 1;

CREATE TABLE KVP (
  KVP_ID                NUMBER NOT NULL,
  AKTOR_ID              NVARCHAR2(255) NOT NULL,
  ENHET                 NVARCHAR2(255) NOT NULL,
  OPPRETTET_AV          NVARCHAR2(255),
  OPPRETTET_DATO        TIMESTAMP,
  OPPRETTET_BEGRUNNELSE CLOB,
  AVSLUTTET_AV          NVARCHAR2(255),
  AVSLUTTET_DATO        TIMESTAMP,
  AVSLUTTET_BEGRUNNELSE CLOB,
  CONSTRAINT KVP_PK PRIMARY KEY (KVP_ID),
  CONSTRAINT KVP_AKTOR_ID_FK FOREIGN KEY (AKTOR_ID) REFERENCES OPPFOLGINGSTATUS (AKTOR_ID)
);

CREATE INDEX KVP_AKTOERID_INDEX
  ON KVP (AKTOR_ID);

ALTER TABLE OPPFOLGINGSTATUS
  ADD GJELDENDE_KVP NUMBER;

ALTER TABLE OPPFOLGINGSTATUS
  ADD CONSTRAINT KVP_FK FOREIGN KEY (GJELDENDE_KVP)
REFERENCES KVP (KVP_ID);

-- ALTER TABLE OPPFOLGINGSTATUS DROP CONSTRAINT  KVP_FK;
-- ALTER TABLE OPPFOLGINGSTATUS DROP COLUMN GJELDENDE_KVP;
-- DROP TABLE KVP;
-- DROP SEQUENCE KVP_SEQ;