ALTER TABLE KVP ADD OPPRETTET_KODEVERKBRUKER VARCHAR2(255) DEFAULT 'NAV' NOT NULL;
ALTER TABLE KVP ADD AVSLUTTET_KODEVERKBRUKER VARCHAR2(255) DEFAULT 'NAV' NOT NULL;
ALTER TABLE KVP ADD CONSTRAINT FK_OPPRETTET_KODEVERKBRUKER FOREIGN KEY (OPPRETTET_KODEVERKBRUKER) REFERENCES KODEVERK_BRUKER(BRUKER_KODE);
ALTER TABLE KVP ADD CONSTRAINT FK_AVSLUTTET_KODEVERKBRUKER FOREIGN KEY (AVSLUTTET_KODEVERKBRUKER) REFERENCES KODEVERK_BRUKER(BRUKER_KODE);

-- ALTER TABLE KVP DROP CONSTRAINT FK_OPPRETTET_KODEVERKBRUKER;
-- ALTER TABLE KVP DROP CONSTRAINT FK_AVSLUTTET_KODEVERKBRUKER;
-- ALTER TABLE KVP DROP COLUMN OPPRETTET_KODEVERKBRUKER;
-- ALTER TABLE KVP DROP COLUMN AVSLUTTET_KODEVERKBRUKER;