ALTER TABLE BRUKER_REGISTRERING add NUS_KODE VARCHAR(6);
ALTER TABLE BRUKER_REGISTRERING add UTDANNING_AVSLUTTET NUMBER(1,0);
ALTER TABLE BRUKER_REGISTRERING add UTDANNING_GODKJENT_I_NORGE NUMBER(1,0);