CREATE SEQUENCE NYE_BRUKERE_SEQ ORDER;

CREATE TABLE NYE_BRUKERE (
  ID                      NUMBER,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  SELVGAENDE              NUMBER(1) DEFAULT 0 NOT NULL,
  OPPRETTET_TIMESTAMP     TIMESTAMP,
  PRIMARY KEY (ID)
);