drop view DVH_BRUKER_REGISTRERING;
create VIEW DVH_BRUKER_REGISTRERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE
  FROM BRUKER_REGISTRERING
);