ALTER TABLE BRUKER_REGISTRERING add YRKESBESKRIVELSE VARCHAR(50);
ALTER TABLE BRUKER_REGISTRERING add KONSEPT_ID NUMBER;

DROP VIEW DVH_BRUKER_REGISTRERING;
CREATE VIEW DVH_BRUKER_REGISTRERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    -1 AS UTDANNING_BESTATT,
    -1 AS UTDANNING_GODKJENT_NORGE,
    YRKESBESKRIVELSE,
    KONSEPT_ID
  FROM BRUKER_REGISTRERING
);