ALTER TABLE BRUKER_REGISTRERING DROP COLUMN SITUASJON;

ALTER TABLE BRUKER_REGISTRERING MODIFY OPPRETTET_DATO NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY NUS_KODE NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY YRKESPRAKSIS NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY ENIG_I_OPPSUMMERING NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY OPPSUMMERING NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY UTDANNING_BESTATT NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY UTDANNING_GODKJENT_NORGE NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY HAR_HELSEUTFORDRINGER NOT NULL;

