CREATE SEQUENCE OPPFOLGING_FEED_SEQ ORDER;

ALTER TABLE OPPFOLGINGSTATUS 
ADD FEED_ID NUMBER;

UPDATE OPPFOLGINGSTATUS SET FEED_ID = OPPFOLGING_FEED_SEQ.NEXTVAL;
CREATE INDEX OPPFOLGINGSTATUS_FEED_ID_INDEX ON OPPFOLGINGSTATUS (FEED_ID);