create table UTMELDING
(
  AKTOR_ID VARCHAR2(20) NOT NULL,
  ISERV_FRA_DATO TIMESTAMP(6) NOT NULL,
  OPPDATERT_DATO TIMESTAMP(6)
);

ALTER TABLE UTMELDING ADD CONSTRAINT unique_aktor_id UNIQUE(aktor_id);