DROP TABLE OPPFOLGINGSPERIODE;

CREATE TABLE OPPFOLGINGSPERIODE (
  aktoerId VARCHAR(20) NOT NULL,
  veilederId NVARCHAR2(20) NOT NULL,
  sluttDato DATE NOT NULL,
  begrunnelse NVARCHAR2(500) NOT NULL
);

