DROP TABLE OPPFOLGINGSPERIODE;

CREATE TABLE OPPFOLGINGSPERIODE (
  aktorId VARCHAR(20) NOT NULL,
  veilederId NVARCHAR2(20) NOT NULL,
  sluttDato DATE NOT NULL,
  begrunnelse NVARCHAR2(500) NOT NULL,
  oppdatert TIMESTAMP(3) NOT NULL
);

