ALTER TABLE ESKALERINGSVARSEL ADD OPPRETTET_BEGRUNNELSE NVARCHAR2(5000);
ALTER TABLE ESKALERINGSVARSEL ADD AVSLUTTET_BEGRUNNELSE NVARCHAR2(5000);
ALTER TABLE ESKALERINGSVARSEL ADD AVSLUTTET_AV NVARCHAR2(255);
