CREATE TABLE SITUASJON (
  AKTORID VARCHAR(20) NOT NULL,
  OPPFOLGING NUMBER(0,1) NOT NULL,
  MANUELL NUMBER(0,1),
  PRIMARY KEY (AKTORID)
);

CREATE TABLE BRUKERVILKAR (
  AKTORID VARCHAR(20) NOT NULL,
  DATO TIMESTAMP NOT NULL,
  VILKARSTATUS VARCHAR(20),
  TEKST VARCHAR(60),
  FOREIGN KEY (AKTORID) REFERENCES SITUASJON (AKTORID)
)