CREATE VIEW DVH_GJELDENDE_SITUASJON AS (
  SELECT
    OPPDATERT,
    AKTORID,
    OPPFOLGING,
    VEILEDER
  FROM SITUASJON
);

CREATE VIEW DVH_MANUELL_HISTORIKK AS (
  SELECT
    AKTORID,
    MANUELL,
    DATO
  FROM STATUS
);

CREATE VIEW DVH_OPPFOLGINGSHISTORIKK AS (
  SELECT
    OPPDATERT,
    AKTORID,
    STARTDATO,
    SLUTTDATO
  FROM OPPFOLGINGSPERIODE
);
