CREATE INDEX "VEILARBSITUASJON"."OPPFOLGINGSPERIODE_INDEX1" ON "VEILARBSITUASJON"."OPPFOLGINGSPERIODE" ("AKTORID");
CREATE INDEX "VEILARBSITUASJON"."MAL_AKTOERID_INDEX" ON "VEILARBSITUASJON"."MAL" ("AKTORID");
CREATE INDEX "VEILARBSITUASJON"."VILKAR_AKTOERID_INDEX" ON "VEILARBSITUASJON"."BRUKERVILKAR" ("AKTORID");