UPDATE KODEVERK_BRUKER K_BRUKER SET ENDRET = (SELECT OPPRETTET FROM KODEVERK_BRUKER WHERE BRUKER_KODE = K_BRUKER.BRUKER_KODE);
UPDATE KODEVERK_BRUKER K_BRUKER SET ENDRET_AV = (SELECT OPPRETTET_AV FROM KODEVERK_BRUKER WHERE BRUKER_KODE = K_BRUKER.BRUKER_KODE);

ALTER TABLE KODEVERK_BRUKER MODIFY ENDRET NOT NULL;
ALTER TABLE KODEVERK_BRUKER MODIFY ENDRET_AV NOT NULL;

ALTER TABLE MAL MODIFY DATO NOT NULL;
ALTER TABLE MAL MODIFY ENDRET_AV NOT NULL;