ALTER TABLE OPPFOLGINGSPERIODE
  ADD STARTDATO TIMESTAMP(6);

ALTER TABLE OPPFOLGINGSPERIODE
  MODIFY VEILEDER VARCHAR(20) NULL;
ALTER TABLE OPPFOLGINGSPERIODE
  MODIFY SLUTTDATO TIMESTAMP(6) NULL;
ALTER TABLE OPPFOLGINGSPERIODE
  MODIFY BEGRUNNELSE NVARCHAR2(500) NULL;

INSERT INTO OPPFOLGINGSPERIODE (AKTORID, VEILEDER, STARTDATO, SLUTTDATO, BEGRUNNELSE, OPPDATERT)
  SELECT
    AKTORID,
    VEILEDER,
    CURRENT_TIMESTAMP,
    NULL,
    NULL,
    CURRENT_TIMESTAMP
  FROM SITUASJON
  WHERE OPPFOLGING = 1;
