package no.nav.veilarboppfolging.kandidatForUtmelding

enum class KandidatForUtmeldingTag {
    ARBEIDSSOKERPERIODE_AVSLUTTET_IKKE_LEVERT_MELDEKORT,
    ARBEIDSSOKERPERIODE_AVSLUTTET_SVARTE_NEI_I_BEKREFTELSE,
    ARBEIDSSOKERPERIODE_AVSLUTTET_ANNET,
    ARBEIDSSOKERPERIODE_AVSLUTTET_BRUKER,
    ARBEIDSSOKERPERIODE_AVSLUTTET_VEILEDER,
    ARBEIDSSOKERPERIODE_AVSLUTTET_SYSTEM,
    ARBEIDSSOKERPERIODE_AVSLUTTET_UKJENT,
}

