ALTER TABLE STATUS DROP CONSTRAINT FK_OPPRETTET_AV;
ALTER TABLE KODEVERK_BRUKER DROP COLUMN ID;
ALTER TABLE KODEVERK_BRUKER ADD CONSTRAINT KODEVERK_BRUKER_BRUKER_KODE_pk PRIMARY KEY (BRUKER_KODE);

TRUNCATE TABLE STATUS;
ALTER TABLE STATUS MODIFY OPPRETTET_AV VARCHAR(255) NOT NULL;
ALTER TABLE STATUS ADD CONSTRAINT FK_OPPRETTET_AV FOREIGN KEY (OPPRETTET_AV) REFERENCES KODEVERK_BRUKER (BRUKER_KODE);