DROP VIEW DVH_GJELDENDE_SITUASJON;
DROP VIEW DVH_MANUELL_HISTORIKK;
DROP VIEW DVH_OPPFOLGINGSHISTORIKK;

ALTER TABLE SITUASJON RENAME TO OPPFOLGINGSTATUS;
ALTER TABLE OPPFOLGINGSTATUS RENAME COLUMN OPPFOLGING TO UNDER_OPPFOLGING;
ALTER TABLE OPPFOLGINGSTATUS RENAME COLUMN GJELDENDE_STATUS TO GJELDENDE_MANUELL_STATUS;
ALTER TABLE OPPFOLGINGSTATUS RENAME COLUMN AKTORID TO AKTOR_ID;

ALTER TABLE STATUS RENAME TO MANUELL_STATUS;
ALTER TABLE MANUELL_STATUS RENAME COLUMN DATO TO OPPRETTET_DATO;
ALTER TABLE MANUELL_STATUS RENAME COLUMN AKTORID TO AKTOR_ID;

ALTER TABLE MAL RENAME COLUMN AKTORID TO AKTOR_ID;

ALTER TABLE BRUKERVILKAR RENAME COLUMN AKTORID TO AKTOR_ID;

ALTER TABLE OPPFOLGINGSPERIODE RENAME COLUMN AKTORID TO AKTOR_ID;


CREATE VIEW DVH_GJELDENDE_OPPFOLGINGSTATUS AS (
  SELECT
    OPPDATERT,
    AKTOR_ID,
    UNDER_OPPFOLGING,
    VEILEDER
  FROM OPPFOLGINGSTATUS
);

CREATE VIEW DVH_MANUELL_HISTORIKK AS (
  SELECT
    AKTOR_ID,
    MANUELL,
    OPPRETTET_DATO
  FROM MANUELL_STATUS
);

CREATE VIEW DVH_OPPFOLGINGSHISTORIKK AS (
  SELECT
    OPPDATERT,
    AKTOR_ID,
    STARTDATO,
    SLUTTDATO
  FROM OPPFOLGINGSPERIODE
);
