CREATE TABLE VEILEDER_TILORDNINGER (
  AKTOR_ID VARCHAR(20) NOT NULL,
  VEILEDER VARCHAR(20) NOT NULL,
  SIST_TILORDNET TIMESTAMP,
  LAGT_INN_AV_VEILEDER VARCHAR(20)
);

INSERT INTO VEILEDER_TILORDNINGER (AKTOR_ID, VEILEDER, SIST_TILORDNET)
SELECT AKTOR_ID, VEILEDER, SIST_TILORDNET FROM OPPFOLGINGSTATUS WHERE VEILEDER IS NOT NULL AND SIST_TILORDNET IS NOT NULL;