CREATE TABLE VEILEDER_TILLORDNINGER (
  AKTOR_ID VARCHAR(20) NOT NULL,
  VEILEDER VARCHAR(20) NOT NULL,
  SIST_TILORDNET TIMESTAMP,
  PRIMARY KEY (AKTOR_ID,VEILEDER, SIST_TILORDNET)
);

INSERT INTO VEILEDER_TILLORDNINGER (AKTOR_ID, VEILEDER, SIST_TILORDNET)
SELECT AKTOR_ID, VEILEDER, SIST_TILORDNET FROM OPPFOLGINGSTATUS WHERE VEILEDER IS NOT NULL AND SIST_TILORDNET IS NOT NULL;