CREATE TABLE SISTE_ENDRING_OPPFOELGING_BRUKER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    FODSELSNR VARCHAR(33) NOT NULL UNIQUE,
    SIST_ENDRET_DATO TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);