CREATE TABLE SAK (
    ID BIGSERIAL PRIMARY KEY,
    OPPFOLGINGSPERIODE_UUID UUID CHAR(36),
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT OPPFOLGINGSPERIODE_UUID_FK FOREIGN KEY (OPPFOLGINGSPERIODE_UUID) REFERENCES OPPFOLGINGSPERIODE (UUID)
);