CREATE TABLE KODEVERK_BRUKER (
  id NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  bruker_kode VARCHAR(255) NOT NULL,
  bruker_beskrivelse VARCHAR(255) NOT NULL,
  opprettet TIMESTAMP NOT NULL,
  opprettet_av VARCHAR(255) NOT NULL,
  endret TIMESTAMP,
  endret_av VARCHAR(255),
  PRIMARY KEY (id)
);

ALTER TABLE STATUS
  ADD opprettet_av NUMBER;

ALTER TABLE STATUS
  ADD opprettet_av_brukerid VARCHAR(255);

ALTER TABLE STATUS
  ADD CONSTRAINT fk_opprettet_av FOREIGN KEY (opprettet_av) REFERENCES KODEVERK_BRUKER(id);
