CREATE TABLE SITUASJON (
  AKTORID VARCHAR(20) NOT NULL,
  OPPFOLGING NUMBER(1,0) NOT NULL,
  MANUELL NUMBER(1,0),
  PRIMARY KEY (AKTORID)
);

CREATE TABLE BRUKERVILKAR (
  AKTORID VARCHAR(20) NOT NULL,
  DATO TIMESTAMP,
  VILKARSTATUS VARCHAR(20),
  TEKST VARCHAR(60),
  FOREIGN KEY (AKTORID) REFERENCES SITUASJON (AKTORID)
);