CREATE SEQUENCE NYE_BRUKERE_FEED_SEQ ORDER;

CREATE TABLE NYE_BRUKERE_FEED (
  ID                      NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  FEED_ID                 NUMBER,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  SELVGAENDE              NUMBER(1) DEFAULT 0 NOT NULL,
  OPPRETTET_TIMESTAMP     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NYE_BRUKERE_PK" PRIMARY KEY (ID),
  CONSTRAINT "UNIQUE_FEED_ID" UNIQUE (FEED_ID)
);