/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.paw.arbeidssokerregisteret.api.v1;
/** Ukjent verdi settes aldri direkte, men brukes som standardverdi og
for å indikere at en verdi er ukjent for mottaker av melding, dvs at
at den er satt til en verdi som ikke er definert i Avro-skjemaet til mottaker.

FORSINKELSE - Grunnen til avvik mellom kilde og register er generell forsinkelse
				 som oppstår i asynkrone systemer.

RETTING - 	Grunnen til avvik mellom kilde og register er at en feil i kilde er rettet
             med virking bakover i tid. */
@org.apache.avro.specific.AvroGenerated
public enum AvviksType implements org.apache.avro.generic.GenericEnumSymbol<AvviksType> {
  UKJENT_VERDI, FORSINKELSE, RETTING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvviksType\",\"namespace\":\"no.nav.paw.arbeidssokerregisteret.api.v1\",\"doc\":\"Ukjent verdi settes aldri direkte, men brukes som standardverdi og\\nfor å indikere at en verdi er ukjent for mottaker av melding, dvs at\\nat den er satt til en verdi som ikke er definert i Avro-skjemaet til mottaker.\\n\\nFORSINKELSE - Grunnen til avvik mellom kilde og register er generell forsinkelse\\n\\t\\t\\t\\t som oppstår i asynkrone systemer.\\n\\nRETTING - \\tGrunnen til avvik mellom kilde og register er at en feil i kilde er rettet\\n             med virking bakover i tid.\",\"symbols\":[\"UKJENT_VERDI\",\"FORSINKELSE\",\"RETTING\"],\"default\":\"UKJENT_VERDI\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
