name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'alerts/kafka_failed_records_alert.yaml'
      - '.github/workflows/alerts.yml'

concurrency:
  group: deploy_alerts
  cancel-in-progress: true

jobs:
  apply-alerts-dev:
    name: Apply alerts til dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: deploy alerts to dev
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts/kafka_failed_records_alert.yaml

  apply-alerts-prod:
    name: Apply alerts til prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: deploy alerts to prod
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/kafka_failed_records_alert.yaml
