name: AsyncAPI schemas gh pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/asyncApiSchemas.yml'
      - 'src/main/resources/schemas/**'

permissions:
  contents: write

concurrency:
  group: veilarboppfolging.asyncapi.schema
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          folder: src/main/resources/schemas
          target-folder: schemas
