name: AsyncAPI documents gh pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/asyncApiDoc.yml'
      - 'src/main/resources/schemas/**'
permissions:
  contents: write

concurrency:
  group: veilarboppfolging.asyncapi.doc
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: Install AsyncApi/cli
        run: bun install -g @asyncapi/cli@v4.1.1

      - name: Generating HTML from my AsyncAPI document
        working-directory: src/main/resources/schemas
        run: asyncapi generate fromTemplate veilarboppfolging.asyncapi.yml @asyncapi/html-template@3.0.0 --use-new-generator -o ./veilarboppfolging-doc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: src/main/resources/schemas/veilarboppfolging-doc
          target-folder: veilarboppfolgingV1
