name: AsyncAPI documents validate

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/asyncApiValidate.yml'
      - 'src/main/resources/schemas/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: install generator
        run: npm install -g @asyncapi/cli

      - name: generate documentaion (denne tar litt tid)
        working-directory: src/main/resources/schemas
        run: asyncapi validate veilarboppfolging.asyncapi.yml
